name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-bicep:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build Bicep
        run: |
          az bicep build -f ./infra/main.bicep
      - name: Upload Bicep JSON
        uses: actions/upload-artifact@v2
        with:
          name: main-json
          path: ./infra/
      - name: Logout of Azure CLI
        run: az logout

  deploy-backend:
    needs: build-bicep
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Bicep JSON
        uses: actions/download-artifact@v2
        with:
          name: main-json
          path: ./infra/
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Backend Only
        env:
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
          BRANCH: ${{ secrets.BRANCH }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          LOCATION: ${{ secrets.LOCATION }}
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          SWA_NAME: ${{ secrets.SWA_NAME }}
          SWA_SKU: ${{ secrets.SWA_SKU }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
        run: |
            az deployment group create --resource-group $AZURE_RESOURCE_GROUP \
            --template-file ./infra/main.json \
            --parameters \
            deployBackend=true \
            deployFrontend=false \
            location=$LOCATION \
            storageAccountName=$STORAGE_ACCOUNT_NAME \
            blobContainerName=$BLOB_CONTAINER_NAME \
            branch=$BRANCH \
            repositoryToken=$REPOSITORY_TOKEN \
            repositoryUrl=$REPOSITORY_URL \
            swaName=$SWA_NAME \
            swaSku=$SWA_SKU
      - name: Logout of Azure CLI
        run: az logout

  upload-to-blob:
    needs: [build-bicep, deploy-backend]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload Assets to Azure Blob Storage
        env:
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
        run: |
          for file in ./assets/*; do
            az storage blob upload \
              --account-name $STORAGE_ACCOUNT_NAME \
              --container-name $BLOB_CONTAINER_NAME \
              --name "$(basename "$file")" \
              --file "$file" \
              --overwrite true
          done
      - name: Logout of Azure CLI
        run: az logout

  replace-placeholders:
    needs: [build-bicep, deploy-backend, upload-to-blob]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Update Asset Placeholders
        env:
          STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}
          BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
        run: |
          python ./scripts/update-placeholders.py
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatically replaced asset placeholders [skip ci]"
          git push origin main

  deploy-frontend:
    needs: [build-bicep, deploy-backend, upload-to-blob, replace-placeholders]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Bicep JSON
        uses: actions/download-artifact@v2
        with:
          name: main-json
          path: ./infra/
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Frontend Only
        env:
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
          BRANCH: ${{ secrets.BRANCH }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          LOCATION: ${{ secrets.LOCATION }}
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
          SWA_NAME: ${{ secrets.SWA_NAME }}
          SWA_SKU: ${{ secrets.SWA_SKU }}
        run: |
            az deployment group create --resource-group $AZURE_RESOURCE_GROUP \
            --template-file ./infra/main.json \
            --parameters \
            deployBackend=false \
            deployFrontend=true \
            location=$LOCATION \
            storageAccountName=$STORAGE_ACCOUNT_NAME \
            blobContainerName=$BLOB_CONTAINER_NAME \
            branch=$BRANCH \
            repositoryToken=$REPOSITORY_TOKEN \
            repositoryUrl=$REPOSITORY_URL \
            swaName=$SWA_NAME \
            swaSku=$SWA_SKU
      - name: Logout of Azure CLI
        run: az logout
