name: Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Deploy Main Bicep
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        SWA_NAME: 'kc-swa-site-${{ github.sha }}'
        SQL_ADMIN_PASSWORD: ${{ secrets.SQL_ADMIN_PASSWORD }}
        REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        ENDPOINT_NAME: ${{ secrets.ENDPOINT_NAME }}
        PROFILE_NAME: ${{ secrets.PROFILE_NAME }}
        BRANCH: main
        REPOSITORY_URL: https://github.com/kennethcarnes/azure-swa
        SKU: Free
        SKUCODE: S1
        LOCATION: eastus2
      run: |
        az bicep build -f ./main.bicep
        az deployment group create --resource-group $AZURE_RESOURCE_GROUP \
          --template-file ./main.json \
          --parameters sqlAdminPassword=$SQL_ADMIN_PASSWORD \
          repositoryToken=$REPOSITORY_TOKEN tenantId=$TENANT_ID \
          endpointName=$ENDPOINT_NAME profileName=$PROFILE_NAME \
          SWAName=$SWA_NAME branch=$BRANCH repositoryUrl=$REPOSITORY_URL \
          sku=$SKU skucode=$SKUCODE location=$LOCATION

    - name: Logout of Azure CLI
      run: az logout
