#https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux&WT.mc_id=javascript-70241-aapowell
name: Deploy 
on: [push]

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:

      # Checkout code from GitHub
    - uses: actions/checkout@main

      # Login to Azure with OpenID Connect 
    - name: Azure Login
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy swa.bicep
    - name: Deploy swa.bicep
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./deploy/main.bicep
        parameters: swaName=${{ secrets.SWA_NAME }}
        failOnStdErr: false

      # Deploy dns.bicep
    - name: Deploy dns.bicep
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./deploy/dns.bicep
        failOnStdErr: false