name: Deploy to Azure

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Deploy Static Web App with Bicep
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      run: |
        az bicep build -f ./frontend.bicep
        az deployment group create --resource-group $AZURE_RESOURCE_GROUP --template-file ./frontend.json

    - name: Build and Deploy Backend with Bicep
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      run: |
        az bicep build -f ./backend.bicep
        az deployment group create --resource-group $AZURE_RESOURCE_GROUP --template-file ./backend.json

    - name: Build and Deploy Monitoring and Security with Bicep
      env:
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      run: |
        az bicep build -f ./monitoring-security.bicep
        az deployment group create --resource-group $AZURE_RESOURCE_GROUP --template-file ./monitoring-security.json