#https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines
#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux&WT.mc_id=javascript-70241-aapowell
on: [push]

permissions:
      id-token: write
      contents: read

stages:
  - stage: Deployment
    displayname: Deployment
    jobs:
        runs-on: ubuntu-latest
        steps:
          - checkout: self

          - name: Az CLI login
            uses: azure/login@v1
            with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Ensure resource group exists
            uses: azure/CLI@v1
            with:
              inlineScript: |
                      az group create -g ${{ secrets.RESOURCE_GROUP }} -l ${{ secrets.RESOURCE_GROUP_LOCATION }}

          - name: Deploy Bicep
            uses: azure/arm-deploy@v1
            with:
              resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
              subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              template: ./deploy/main.bicep
              parameters: swaName=${{ secrets.SWA_NAME }}
              failOnStdErr: false 