#https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux&WT.mc_id=javascript-70241-aapowell
name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Connect to Azure
      uses: azure/login@v1 
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: 'Run Azure CLI commands'
      run: |
          app=$(az ad app create --display-name blog-deployer -o json)
          appId=$(echo $app | jq -r '.appId')
          objectId=$(echo $app | jq -r '.id')

          sp=$(az ad sp create --id $appId -o json)
          assigneeObjectId=$(echo $sp | jq -r '.id')

          subscriptionId=...
          resourceGroupName=...
          az role assignment create --role contributor --subscription $subscriptionId --assignee-object-id  $assigneeObjectId --assignee-principal-type ServicePrincipal --scope /subscriptions/$subscriptionId/resourceGroups/$resourceGroupName

          credentialName=github-deploy
          subject=repo:kennethcarnes/swa:environment:production
          az rest --method POST --uri "https://graph.microsoft.com/beta/applications/$objectId/federatedIdentityCredentials" --body "{\"name\":\"$credentialName\",\"issuer\":\"https://token.actions.githubusercontent.com\",\"subject\":\"repo:organization/repository:environment:production\",\"description\":\"Deploy from GitHub Actions\",\"audiences\":[\"api://AzureADTokenExchange\"]}"

          echo Values for GitHub secrets:
          echo Client ID: $appId
          echo Tenant ID: $(echo $sp | jq -r '.appOwnerOrganizationId')
          echo Subscription ID: $subscriptionId
        - name: Ensure resource group exists
          uses: azure/CLI@v1
          with:
            inlineScript: |
                    az group create -g ${{ secrets.RESOURCE_GROUP }} -l ${{ secrets.RESOURCE_GROUP_LOCATION }}            
        - name: Deploy Bicep
          uses: azure/arm-deploy@v1
          with:
            resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            template: ./deploy/main.bicep
            parameters: swaName=${{ secrets.SWA_NAME }}
            failOnStdErr: false